name: Build .NET Framework Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.WebDevelopment --quiet --norestart"

    - name: Setup .NET Framework version
      run: |
        # Install the .NET Framework SDK (if needed)
        # .NET Framework is already included on the Windows runner.
        echo "Setting up .NET Framework environment"

    - name: Restore NuGet packages
      run: nuget restore WebApplication.sln

    - name: Build with MSBuild
      run: |
        msbuild WebApplication.sln /p:Configuration=Release
